[package]
name = "endec"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "endec"
crate-type = ["cdylib"]

[dependencies]
encoding_rs = "=0.8.33"
pyo3 = "=0.20.0"
